# This configuration is only for development mode.
# In production mode, the base Dockerfile can be used without
# `docker-compose` (this may change)
version: "3.4"
services:
  frontend:
    build:
      context: ..
      dockerfile: docs/Dockerfile
      # We build to docs-base for development, to allow for auto-reloading
      target: docs-base
    # Run npm install
    command: bin/run-docker
    expose:
      - 8000
    volumes:
      - .:/docs
      - node_modules:/docs/node_modules
      - cache:/docs/.docusaurus
      # Mount the backend code directory to the 'app' folder
      - ../backend:/app
  backend:
    build: python-api
    volumes:
      - py_docs:/docs/build/html
    command: make watch-html
    expose:
      - 5000
  gateway:
    build:
      context: server-config
      dockerfile: Dockerfile.dev
    ports:
      - "8080:80"
    volumes:
      - py_docs:/usr/share/nginx/html/core
volumes:
  cache:
  node_modules:
  py_docs:
